apiVersion: v1
kind: Pod
metadata:
  name: spot-nginx
  labels:
    env: miztiik-prod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    app: miztiik_spot_ng

